### ISSUE TITLE
makeindex returns error 

### ISSUE THREAD

**Issue by cicervlvs** [cicervlvs/langnames#15]
Right now the only way to properly compile `langnames.dtx` is with a simple `lualatex` or `xelatex` command, which doesn't produce an index. If you try to compile the file with `latexmk`, which attempts to make an index, it errors out. Presumably there is something wrong with `langnames.dtx` which precludes `makeindex` from running properly.

**Comment by niruvt** [comment]
Sorry, didn't get notified for this. Just saw this issue.

There is nothing wrong with `langnames.dtx`. The problem is in the command you might be issuing for printing index. One can't simply use `makeindex` as the index seen in package documentations is special! The dtx file requires a special parameter to `makeindex` command which is `-s gglo.ist`, issued as follows:

```bash
makeindex -s gglo.ist -o ⟨package⟩.gls ⟨package⟩.glo
```

The `-s` parameter to `makeindex` means style. People can have their own style files for index. The documentation has some guidelines for that, but I haven't gone into much depth. `gglo.ist` is a style file developed and maintained by the project team. That file determines how the index looks. It's not simple LaTeX. Try directing `latexmk` to add this parameter. This should be solved.

**Comment by cicervlvs** [comment]
Thank you for pointing this out to me! I'll see how I can add that parameter to the latexmk call in the CI workflow.
