### ISSUE TITLE
Package for CTAN update

### ISSUE THREAD

**Issue by cicervlvs** [cicervlvs/langnames#4]

**Comment by niruvt** [comment]
If you haven't yet sent the package to CTAN, may I ask you to hold it? I see another small problem, but needs some testing which at the moment cannot be done. I will do it in the evening.

**Comment by cicervlvs** [comment]
Yes, no problem. I actually meant to ask you to test the package before I ever sent it again

**Comment by niruvt** [comment]
> Yes, no problem. I actually meant to ask you to test the package before I ever sent it again.

Thanks for waiting :) I checked all your commits, they are valid, but I am more worried about [this commit](https://github.com/cicervlvs/langnames/commit/742881972e6aad19302ca11bb59be595df312075). I will try to elaborate my concerns here.

1. As you have changed filenames in this commit too, it would be a significant change to your LaTeX package. Please consider that as soon as something is released, people get access to all the files of your package. Take for example me. Your package only caught my eye when it was installed on my system by a TeX Live script, otherwise I probably wouldn't have come to it ever. The same way some people might have `\input` your data-files in their documents for their own purpose. Now if you suddenly change the file name, it will break all such documents. This shouldn't happen in any programming language. Even if now you don't like the names much; don't think of changing them. Thankfully you have everything related to this change in one commit. I would strongly advise you to revert this commit. I know these cases are rare and hypothetical, but one shall never release breaking changes is what I believe and hence advising you to revert the changes made by that commit entirely.
2. Why the `\unskip` macro? Do you really need it? There is no space behind it as far as I see in any cases. If you are just afraid of the LaTeX behavior of eating up spaces when they aren't supposed to; let me make you assured that this doesn't happen. If you don't have a clear case where _not_ using `\unskip` creates problem, please show me, otherwise let's omit it. I faced some problem because of it while documenting, but I don't remember where exactly it happened.
4. The package option we set is `glottolog`, but the prefix that users are supposed to use `glot` as an argument to `\renewlang`.  Same with `none` and `custom`. I apologize for using inconsistent names, but fortunately we have spotted it before release. We can clean things up before releasing, so that users don't face any problem.

**Comment by niruvt** [comment]
Also I just realized that I provided `\renewlang`, but it actually `\renew`s `lang`s as well as `fams`, so we should either change the name or have two macros. What would you prefer?

**Comment by cicervlvs** [comment]
> As you have changed filenames in this commit too, it would be a significant change to your LaTeX package

I did not consider this, it was just bugging me how the naming was kind of inconsistent. I can't imagine many people have this package already installed on their computers, but if it is such a risk I'm okay with reverting the commit.

> Why the `\unskip` macro?

This was something that I noticed while initially developing the package, the command was printing without a space between it and the next word. This stopped happening when I started using `\unskip`, so I haven't looked back. If you say that it can work without the command, we can also remove it. I want to see it first though haha.

>  The package option we set is `glottolog`, but the prefix that users are supposed to use `glot`...

Sure, we can change this.

> Also I just realized that I provided `\renewlang`, but it actually `\renew`s `langs` as well as `fams`...

When deveolping the package I concieved of `langs` as a combination of `name` and `fam`, so the naming wouldn't be a problem in principle. I think it can stay like that unless you really want to make it two macros.

If you want you can submit all the problems that you see as separate issues, so it's all neat and tidy and we have a clearer view of the project :)

**Comment by niruvt** [comment]
> If you want you can submit all the problems that you see as separate issues, so it's all neat and tidy and we have a clearer view of the project :)

Cool, I will do it soon.

**Comment by niruvt** [comment]
Everything looks ready now. We can publish.

**Comment by cicervlvs** [comment]
Okay, I am making the package now.

**Comment by cicervlvs** [comment]
The package has been uploaded to CTAN. Hopefully we get a response soon

**Comment by niruvt** [comment]
Cool!

If they respond by keeping both of us in the mail that's great, but if only you get the response, share my CTAN author profile with them so that they recognize me. (https://ctan.org/author/niranjan)
